ENH: Provide a pyFAI Geometry Optimization Task
slac-lcls/lute pull request #59
Opened 2024-10-16 00:52 UTC by LouConreux

# Description

## Checklist

- [ ] <Feature 1>

## PR Type:

- [ ] New feature/Enhancement
- [ ] Bug fix
- [ ] CI/CD
- [ ] Documentation
- [ ] Style/Maintenance
- [ ] Testing

## Address issues:

- Use syntax like: `Closes #1`

# Testing

# Screenshots

2025-02-25 16:30 UTC, gadorlhiac requested changes
Hi @LouConreux , thanks for your work on this! I've left some first pass comments to start that are mostly structural.

One major thing to consider is if there is a benefit to having more than 1 starting distance (with the trade-off of longer processing time). This is particularly relevant if we're still having trouble running on multiple nodes.

I think it would also be helpful if maybe we have a short documentation page with some guidelines (maybe somewhere in `docs/usage`, we can add some Task-specific sub-header), since in this case it may not be immediately obvious to a user which kernel or preprocessing step to use.

2025-02-25 16:30 UTC, gadorlhiac commented on config/templates/smd_producer_template.py
> +        if 'max' in key:
Thanks for adding this! I forgot to update the template, although it has been updated in the actual `smalldata_tools` repository.

2025-02-25 16:30 UTC, gadorlhiac commented on lute/execution/logging.py
> +        elif "pyFAI" in other_name and not isinstance(
Are there any potentially useful warnings that may be lost by disabling this logger? It seems unlikely for the other one to me, but I suppose there may also be something there.

2025-02-25 16:30 UTC, gadorlhiac commented on lute/io/models/bayfai.py
> +            description="Bounds defining the parameter search space for the Bayesian optimization.",
Perhaps we could add units for the bounds in the description.

2025-02-25 16:30 UTC, gadorlhiac commented on lute/io/models/bayfai.py
> +            description="Resolution of the grid used to discretize the parameter search space.",
Same thing, units for resolution would be helpful.

2025-02-25 16:30 UTC, gadorlhiac commented on lute/io/models/bayfai.py
> +            description="Kernel to be used by the Gaussian Process for the Bayesian optimization.",
Can we add a list of supported kernels?

2025-02-25 16:30 UTC, gadorlhiac commented on lute/io/models/bayfai.py
> +            description="Acquisition function to be used by the Bayesian optimization.",
Same thing, a list of supported options would be useful.

I think in the main doc string (or elsewhere, open to ideas) we could also put a description of the equation so that people can know how to change the hyper parameters.

2025-02-25 16:30 UTC, gadorlhiac commented on lute/io/models/bayfai.py
> +    exp: str = Field(
I think we can clean up `exp`, `run`, and `work_dir` along with their validators. These are just taking the values that are already in `lute_config`.

The code in the `Task` will only need to be updated to use `self._task_parameters.lute_config.exp` etc. but it will make the model cleaner.

2025-02-25 16:30 UTC, gadorlhiac commented on lute/io/models/validators.py
> +import psana  # type: ignore
I'm slightly concerned about these two imports. Is there any way to make the validator work without them?

The issue is that the code in this module may be imported in `Task`s that do not have `psana` in the environment and we'd get an error.

My first choice would be to see if this can be done without the imports (since I think it's mostly looking for a file path which should be mostly deterministic). We can discuss maybe a back up of moving the imports into the validator, or putting some exception handling in place, but this is less ideal.

2025-02-25 16:30 UTC, gadorlhiac commented on workflows/airflow/bayfai.py
> +geom_optimizer: JIDSlurmOperator = JIDSlurmOperator(max_cores=120, task_id="PyFAIGeometryOptimizer", dag=dag)
Were you able to investigate/resolve the issue when running on multiple nodes? If not should this be forced to run on a single node?

2025-02-25 16:30 UTC, gadorlhiac commented on lute/tasks/bayfai.py
> +import matplotlib.pyplot as plt  # type: ignore
We may be able to update our GH action to install necessary files to remove some of these `type: ignore`.

2025-02-25 16:30 UTC, gadorlhiac commented on lute/tasks/bayfai.py
> +sys.path.append("/sdf/home/l/lconreux/LCLSGeom")
Do we know when this will be added to the environment? I'd prefer not to merge with these type of PATH manipulation since they tend to be fragile.

If there is no immediate timeline for getting this into the environment, we can discuss alternatives.

2025-02-25 16:30 UTC, gadorlhiac commented on lute/tasks/bayfai.py
> +    Parameters
Can we update the docstring formatting to the google style? The README has examples, or the other Tasks can be used as a model.

This will be needed for properly generating the documentation pages.


As a separate note, we should add the code documentation page which involves putting a markdown file in the appropriate directories: [docs/source/tasks](https://github.com/slac-lcls/lute/tree/dev/docs/source/tasks)

The file just needs to have this in it:
```md
::: tasks.bayfai
```

We can update the navigation in the YAML file: [here](https://github.com/slac-lcls/lute/blob/ccd4ceddaf815dc9748e4d56e3c701a29ff51cd5/mkdocs.yml#L13)

2025-02-25 16:30 UTC, gadorlhiac commented on lute/tasks/bayfai.py
> +class BayesGeomOpt:
Since this module has gotten quite long, would it make sense to put this class in a utility module?

2025-02-25 16:30 UTC, gadorlhiac commented on lute/tasks/bayfai.py
> +            plots = pn.Tabs(fig)
Would it make sense to add direct support for matplotlib figures [here](https://github.com/slac-lcls/lute/blob/ccd4ceddaf815dc9748e4d56e3c701a29ff51cd5/lute/tasks/dataclasses.py#L87)

2025-02-25 16:30 UTC, gadorlhiac commented on lute/tasks/bayfai.py
> +        self.order = ["dist", "poni1", "poni2", "rot1", "rot2", "rot3"]
Minor note that Python dictionaries are ordered, so you can use the keys of your dict below.

2025-02-25 16:30 UTC, gadorlhiac commented on lute/tasks/bayfai.py
> +        runner = next(ds.runs())
Can't we just use `self.run` - the additional calls return the same number back to you, correct?

2025-02-25 16:30 UTC, gadorlhiac commented on lute/tasks/bayfai.py
> +        dist = self.comm.scatter(distances, root=0)
Is there a use-case for having more than 120 starting points tested? Particularly if there are still issues running across multiple nodes?

I wonder if it would be worthwhile to add the option to run optimize multiple distances per rank?

2025-02-25 16:30 UTC, gadorlhiac commented on lute/tasks/bayfai.py
> +    def bayes_opt_animation(
Does this method get used?

2025-02-25 16:30 UTC, gadorlhiac commented on lute/tasks/bayfai.py
> +    def radial_integration(self, result, calibrant=None, label=None, ax=None):
I'd suggest changing the name here to make it more clear that it is a plot and doesn't do radial integration.

Same for some of the other methods (`score_distance_scan`, `residual_distance_scan`, etc...)

2025-02-27 19:24 UTC, LouConreux commented on lute/execution/logging.py
> +        elif "pyFAI" in other_name and not isinstance(
No I don't think so, pyFAI is mostly returning a lot of INFO, since I am calling pyFAI a lot within the code, my useful logs are lost among the rest. About the other one, I try to find a way to disable useless logs when importing pyFAI, but so far, I did not manage to find a solution.
See this for more info: [silent warnings openCL](https://github.com/silx-kit/pyFAI/issues/788)

Maybe we can get rid of that second part.

2025-02-27 19:24 UTC, LouConreux commented on lute/io/models/validators.py
> +import psana  # type: ignore
Will try to correct that okay!

2025-02-27 19:24 UTC, LouConreux commented on workflows/airflow/bayfai.py
> +geom_optimizer: JIDSlurmOperator = JIDSlurmOperator(max_cores=120, task_id="PyFAIGeometryOptimizer", dag=dag)
I don't know what is happening exactly. 

"Half" of the time when running on multiple nodes, it is running without any issues. The other "half", the code seems to run fine on each rank, however it seems that when trying to gather all the results at the root rank, it somehow freezes and the job never terminates. I think this happened when running on a lot of different nodes. Nothing is written inside the logs, and the job does not even terminate past the time limit fixed in the yaml. Could it be something related to MPI ? 

So I would recommend adding the `--nodes=1` for my task in particular.

2025-02-28 23:47 UTC, LouConreux commented on lute/tasks/bayfai.py
> +    def bayes_opt_animation(
Nope, it was just for my final presentation

2025-02-28 23:47 UTC, LouConreux commented on lute/tasks/bayfai.py
> +    def radial_integration(self, result, calibrant=None, label=None, ax=None):
Changed it!

2025-02-28 23:53 UTC, LouConreux commented on lute/tasks/bayfai.py
> +        dist = self.comm.scatter(distances, root=0)
Honestly, I did not think of any other use-case rather than:

1. If provided a distance guess, go for 101 scanned distances (so that you have a 1mm step size between two distances), hence requiring 102 cores
2. If provided bounds, I guess it could be useful to use as much ranks as required by your desired step size (if want to cover 200mm then one would need 201 ranks to have a 1mm step size). 

But I have not tested that given that there is issues with running on multiple nodes and I dont have a clue why... 

Ideally, it would be nice. But since here we are mainly relying on a distance guess, I don't know if that is worth looking into it.

2025-10-02 23:18 UTC, gadorlhiac requested changes
Hi @LouConreux , thank you! I think this looks good. There are a couple minor things (mostly to fix the documentation - which is great btw!). Then we can merge.

2025-10-02 23:18 UTC, gadorlhiac commented on docs/usage/tasks/bayfai/bayfai.md
> +
Thank you for the documentation!

Can you add this to the mkdocs.yml? It won't appear automatically. E.g.:
```yaml
  - Usage Manual:
      - Task Configuration: "usage/configuration.md"
      - Running LUTE: "usage/running_lute.md"
      - Task Documentation:
          - BayFAI: "usage/tasks/bayfai/bayfai.md"
```

2025-10-02 23:18 UTC, gadorlhiac commented on lute/execution/executor.py
> +                    )
I think you want this to be changed to `env[key] = ....{env[key]}"`

2025-10-02 23:18 UTC, gadorlhiac commented on lute/io/models/validators.py
> +def validate_calib_path(calib_path_name: str):
Could we update this name to something a little more specific. `calib_path` could refer to many things. 

Alternatively, the function is also seemingly BayFAI specific, so maybe we just move it into the `bayfai.py` module? (Because it searches for names of fields that are only in the BayFAI model).

2025-10-02 23:18 UTC, gadorlhiac commented on lute/io/models/validators.py
> +def validate_output_path(output_path_name: str):
Same as `validate_calib_path`

2025-10-02 23:18 UTC, gadorlhiac commented on lute/tasks/tasklets.py
> +    python_path: Optional[str] = os.getenv("PYTHONPATH")
Do you need this here (the part to update the environment)? I don't think this environment change is going to do work here.

Ideally we wouldn't use tasklets for this (since there are specific mechanisms for it).

2025-10-02 23:18 UTC, gadorlhiac commented on utilities/setup_lute
> +        "-d",
This one conflicts with the `-d | --debug` option a bit above. Can just remove the `-d` to make it unambiguous.

2026-01-27 17:14 UTC, gadorlhiac approved these changes
Thank you @LouConreux ! Will merge this in.

2026-01-27 17:14 UTC, merged